### ISSUE TITLE
Array values being transformed

### ISSUE THREAD

**Issue by tmclaugh** [BinaryThumb/change-case-object#7]
I'm not sure if the behavior regarding array values is correct.

https://github.com/BinaryThumb/change-case-object/blob/master/index.js#L9-L15

Arrays only contain values so if the value is a string, and not another object, is should likely have its case remain unchanged. I noticed this while trying to return some AWS EC2 instance information and found my instance IDs going from kebab case to snake case.  How should this be handled?  Optional flag on functions so compatibility is preserved?

**Comment by ddmng** [comment]
Hi @tmclaugh ,
I have the same issue, have you find a workaround in the meantime?

**Comment by tmclaugh** [comment]
@ddmng I'm not even sure what caused me to file this anymore.

**Comment by ddmng** [comment]
We're close the this issue's 2nd birthday!
Anyway, if you need, I fixed it in https://github.com/ddmng/change-case-object/commit/21ab167056ba512331f85745ab4d707820215309 but suspect that the original behaviour was intentional for some reason

**Comment by brycesenz** [comment]
I would be a big fan of this being merged into this main project, at least as a configurable option.

**Comment by swapnil2993** [comment]
Is this fix going to be released?

**Comment by markusand** [comment]
Already 2021 and this bug isn't fixed, nor @ddmng 's PR accepted. I'm just facing this problem with an object containing an array of string dates in ISO-8601.

```javascript
{
    available_dates: ['2021-03-01T00:00:00Z', '2021-03-02T00:00:00Z', '2021-03-03T00:00:00Z'],
}
```

Dates are converted `2021-03-03T00:00:00Z` being converted to `2021_03_03T00:00:00Z`, even with camelCase() being used.
